### ISSUE TITLE
calctweet.py で3つの誤認識

### ISSUE THREAD

**Issue by fgophi** [fgophi/fgosccalc#25]
https://twitter.com/tenkou_64/status/1276136859693793280

以下の誤認識
- 画像1: 術魔6222→術魔715222
- 画像1: 狂輝7295→狂輝5
- 画像2: 術魔6269→術魔715269

```
$ calctweet.py -u https://twitter.com/tenkou_64/status/1276136859693793280 -d
(略)
画像1,羽根,4,鉄杭,59,術魔,715222,狂輝,5,泥無しアイテム1_,,
(略)
画像2,羽根,59,鉄杭,179,術魔,715269,狂輝,7380,泥無しアイテム1_,,
(略)
```
![image](https://user-images.githubusercontent.com/62515228/85851293-5c2df480-b7e9-11ea-8d22-f8fa84a03f1d.png)
![image](https://user-images.githubusercontent.com/62515228/85851326-6c45d400-b7e9-11ea-84a8-7c259abf5183.png)

**Comment by fgophi** [comment]
img2str.py fgosccalc.pyだと画像1: 狂輝7295→狂輝5のみ
```
$ img2str.py image\1276136859693793280_0.jpg
【セイレム 空き家】羽根4-鉄杭59-術魔15222-狂輝5
```
```
$ fgosccalc.py image\1276136859693793280_0.jpg image\1276136859693793280_1.jpg --loglevel DEBUG
[DEBUG] sc1: [('羽根', '4'), ('鉄杭', '59'), ('術魔', '15222'), ('狂輝', '5')]
[DEBUG] sc2: [('羽根', '59'), ('鉄杭', '179'), ('術魔', '15269'), ('狂輝', '7380')]
【セイレム 空き家】000周
羽根55-鉄杭120
術魔47-狂輝7375
術猛火NaN
#FGO周回カウンタ http://aoshirobo.net/fatego/rc/
```

**Comment by fgophi** [comment]
画像1: 狂輝7295→狂輝5は #26 で修正されるまで所持数が表示されなかったやつ
detect_first_digit_height()の
threshold = 140
を
threshold = 150
にすると正常認識されるが、この変更が他の画像に影響しないか調査中

**Comment by amenohimo** [comment]
自動しきい値選択をする
`dummy, tmpimg2 = cv2.threshold(tmpimg, 0, 255, cv2.THRESH_OTSU)`
を試してみてはいかがでしょうか

**Comment by fgophi** [comment]
#27 で修正されました
